plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'groovy'
}

group = 'com.artur114.armoredarms.gradle'
archivesBaseName = 'ArmoredArmsCoreBuild'
version = corePluginVersion

dependencies {
    compile gradleApi()
    compile localGroovy()
}

gradlePlugin {
    plugins {
        coreBuild {
            implementationClass = 'com.artur114.armoredarms.gradle.CoreBuildPlugin'
            id = 'core-build'
        }
    }
}

jar {
    manifest {
        attributes([
                "Implementation-Version"  : "${version}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "Implementation-Vendor"   : author
        ])
    }
}

task testAny {
    FileTree tree = project.fileTree(dir: 'build').include('**/*-deobf.jar') as FileTree

    tree.each { File file ->
        println file.name
    }
}

apply from: rootProject.file("scripts/base.gradle")
apply from: rootProject.file("scripts/publish.gradle")