buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.github.Artur114Projects.Armored_Arms:core-plugin:1.3.0-core'
    }
}
plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

apply plugin: 'core-plugin'

base {
    version = 'v' + mod_version
    group = mod_group_id
    archivesName = archives_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
}

coreBuildConf {
    resourcesConf {
        replaceProperties([
                minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
                forge_version: forge_version, forge_version_range: forge_version_range,
                loader_version_range: loader_version_range,
                mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                mod_authors: mod_authors, mod_description: mod_description,
        ])

        includeFiles 'META-INF/mods.toml', 'pack.mcmeta'
    }

    jarConf {
        author = "@mod_authors@"
        return
    }
}

dependencies {
    implementation fg.deobf("curse.maven:minecraft-comes-alive-reborn-535291:8900572")
    implementation fg.deobf("curse.maven:better-combat-by-daedelus-639842:7287334")
    implementation fg.deobf("curse.maven:cosmetic-armor-reworked-237307:4600191")
    implementation fg.deobf("curse.maven:satsu-iron-man-addon-1189482:8858946")
    implementation fg.deobf("curse.maven:threetag-palladium-963363:8716074")
    implementation fg.deobf("curse.maven:mm-modern-mayhem-1328893:7703251")
    implementation fg.deobf("curse.maven:vics-point-blank-961053:7664533")
    implementation fg.deobf("curse.maven:fracture-point-1207137:8673148")
    implementation fg.deobf("curse.maven:scorched-guns-802940:7232063")
    implementation fg.deobf("curse.maven:aether-255308:6134920")
    implementation fg.deobf("curse.maven:punchy-1374153:8029969")
    implementation fg.deobf("curse.maven:curios-309927:6418456")

    implementation fg.deobf("curse.maven:entity-model-features-844662:8063556")
    implementation fg.deobf("curse.maven:entity-texture-features-fabric-568563:7818911")

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    core.massDependencies {
        source "libs"

        deObfHook {fg.deobf(it)}
    }
}

mixin {
    add sourceSets.main, 'mixins.armoredarms.refmap.json'
    config 'mixins.armoredarms.json'
}