buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven {
            url = uri("https://maven.pkg.github.com/Artur114Projects/Armored_Arms")
            credentials {
                // Replace this with your git hub token, or add the git hub token to global gradle.properties
                username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'com.artur114.armoredarms.gradle:core-build:1.2.1'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'core-build'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
    if (atfile != "null") {
        accessTransformer = file('src/main/resources/META-INF/' + atfile)
    }
    runs {
        client {
            workingDirectory this.project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            if (this.project.findProperty("coreModClass") != "null") {
                jvmArg '-Dfml.coreMods.load=' + this.project.findProperty("coreModClass")
            }
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            if (this.project.findProperty("coreModClass") != "null") {
                jvmArg '-Dfml.coreMods.load=' + this.project.findProperty("coreModClass")
            }
        }
    }
}

coreBuildConf {
    dependenciesConf {
        ghPackages {
            credentials {
                // Replace this with your git hub token, or add the git hub token to global gradle.properties
                it.password = "@gpr.key@"
                it.username = "@gpr.user@"
            }
        }
    }

    jarConf {
        atFile = "aa_at.cfg"
        return
    }
}

configurations {
    apiCompile.extendsFrom compile
}

sourceSets {
    api {
        java {
            srcDirs = ['src/api/java']
        }
        compileClasspath += this.project.configurations.getByName("apiCompile")
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:24.0.0'

    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859'
    compileOnly sourceSets.api.output

    core.massDependencies {
        source "libs"

        deObfHook {fg.deobf(it)}
    }
}

jar.finalizedBy('reobfJar')