plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.148'
    id 'core-build' version '1.2.1'
    id 'idea'
}

base {
    version = 'v' + mod_version
    group = mod_group_id
    archivesName = archives_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version

    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = parchment_minecraft_version
    }
}

repositories {
    mavenLocal()
}

coreBuildConf {
    doLoadProjectData = false

    dependenciesConf {
        afterDependence "curse.maven:entity-texture-features-fabric-568563:9055219"
        afterDependence "curse.maven:minecraft-comes-alive-reborn-535291:8658484"
        afterDependence "curse.maven:cosmetic-armor-reworked-237307:5610814"
        afterDependence "curse.maven:entity-model-features-844662:9064965"
        afterDependence "curse.maven:vics-point-blank-961053:8855569"
        afterDependence "curse.maven:playeranimator-658587:7389814"
        afterDependence "curse.maven:azurelib-817423:9095629"
        afterDependence "curse.maven:geckolib-388172:8893490"
        afterDependence "curse.maven:punchy-1374153:9004863"
        afterDependence "curse.maven:create-328085:7963363"
        afterDependence "curse.maven:curios-309927:6529130"

        coreConf {
            version = "@core_version@"
            return
        }

        ghPackages {
            credentials {
                // Replace this with your git hub token, or add the git hub token to global gradle.properties
                it.password = "@gpr.key@"
                it.username = "@gpr.user@"
            }
        }
    }

    resourcesConf {
        replaceProperties([
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
        ])

        includeFiles 'META-INF/neoforge.mods.toml', 'pack.mcmeta'
    }

    jarConf {
        coreVersion = "@core_version@"
        author = "@mod_authors@"
        return
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}