pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven {
            name = 'GitHubPackages'
            url = 'https://maven.pkg.github.com/Artur114Projects/Armored_Arms'
            credentials {
                // Replace this with your build data, or add the value data to global gradle.properties
                username = settings.getProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                password = settings.getProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
            }
        }
        mavenLocal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}